# Generated by Django 4.1.10 on 2023-07-09 16:22

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_ids", djongo.models.fields.JSONField()),
                ("settled_amount", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Settlement",
                "verbose_name_plural": "Settlements",
            },
        ),
    ]
